CREATE TABLE guilds ();
CREATE TABLE _migrations ();
ALTER TABLE guilds ADD COLUMN id NUMERIC;
ALTER TABLE guilds ADD COLUMN allowed_channels NUMERIC[];
ALTER TABLE guilds ADD COLUMN blacklisted_roles NUMERIC[];
ALTER TABLE _migrations ADD COLUMN id_ INTEGER;
ALTER TABLE guilds ALTER COLUMN id SET NOT NULL;
ALTER TABLE guilds ALTER COLUMN allowed_channels SET NOT NULL;
ALTER TABLE guilds ALTER COLUMN blacklisted_roles SET NOT NULL;
ALTER TABLE _migrations ALTER COLUMN id_ SET NOT NULL;
ALTER TABLE guilds ADD CONSTRAINT _guilds_id_primary_key PRIMARY KEY ( id );
ALTER TABLE _migrations ADD CONSTRAINT __migrations_id__primary_key PRIMARY KEY ( id_ );